---

- name: Determine if general mysql packages exist on Redhat system base
  command: /bin/rpm -q mysql-libs
  when: ansible_os_family == 'RedHat'
  register: if_found
  ignore_errors: yes

- name: If found, run rpm erase
  include: rpm-erase.yml
  when: ansible_os_family == 'RedHat' and if_found.rc == 0

- name: Remove MySQL from CentOS 5 base
  yum: name=mysql state=absent
  when: ansible_os_family == 'RedHat' and ansible_distribution_major_version|int < 6

- name: Install MySQL packages on Redhat base
  yum: name={{item}} state=latest
  with_items: 
  - mysql55
  - mysql55-devel
  ignore_errors: yes
  when: ansible_os_family == 'RedHat'

- name: Install MySQL packages on Ubuntu base
  apt: name={{item}} state=present
  with_items: 
  - libmysqlclient15-dev
  - mysql-client
  when: ansible_distribution == "Ubuntu"

- name: Install MySQL packages on Debian base
  apt: name={{item}} state=present
  with_items:
  - libmysqlclient-dev
  - mysql-client
  when: ansible_distribution == "Debian"


