---

- name: Install the varnish repo - RHEL
  yum: name=http://repo.varnish-cache.org/redhat/varnish-3.0/el5/noarch/varnish-release/varnish-release-3.0-1.noarch.rpm state=present
  when: ansible_os_family == 'RedHat'

- name: Install varnish from repo - RHEL
  yum: name=varnish state=present
  when: ansible_os_family == 'RedHat'

- name: Move default vcl
  command: mv /etc/varnish/default.vcl /etc/varnish/default.vcl.orig

- name: Download varnish vcl and place in proper location
  template: src=cent-vcl.j2 dest=/etc/varnish/default.vcl

- name: Change port.conf - RHEL
  command: sed -i "s/Listen 80\$/Listen $BACKEND_PORT/g" /etc/httpd/ports.conf
  when: ansible_os_family == 'RedHat'

- command: sed -i "s/NameVirtualHost \*:80\$/NameVirtualHost \*:$BACKEND_PORT/g" /etc/httpd/ports.conf
  when: ansible_os_family == 'RedHat'

- name: Change vhosts - RHEL 
  command: sed -i "s/:80>/:$BACKEND_PORT>/g" /etc/httpd/vhost.d/*
  when: ansible_os_family == 'RedHat'

- name: Change varnish listen port - RHEL
  command: sed -i 's/VARNISH_LISTEN_PORT=6081$/VARNISH_LISTEN_PORT=80/g' /etc/sysconfig/varnish
  when: ansible_os_family == 'RedHat'

- name: Restart apache - RHEL
  service: name=httpd state=restarted
  when: ansible_os_family == 'RedHat'

- name: Start and chkconfig varnish
  service: name=varnish state=started enabled=yes
  when: ansible_os_family == 'RedHat'
